<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<PackageId>Roo.Azure.Configuration.Common.Http</PackageId>
	<Company>rooged</Company>
	<PackageTags>dotnet;Azure;.NET8;HTTP;microservices;C#;</PackageTags>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.14.2" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.8.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="8.10.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	<None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Roo.Azure.Configuration.Common\Roo.Azure.Configuration.Common.csproj" />
  </ItemGroup>

</Project>
